### ISSUE TITLE
Couldn't find <compress> option

### ISSUE THREAD

**Issue by nitinsurana** [gabrysbiz/lesscss-maven-plugin#1]
Is there a compress option just like the outdated official lesscss-maven-plugin, because I have used it and it doesn't seem to work.

**Comment by nitinsurana** [comment]
Also, how to force compile, for the 2nd run it doesn't compile again.

**Comment by nitinsurana** [comment]
&lt;compress&gt; doesn't really work, it compresses always!

2nd run compiles if the files to be included (.css or .less) are changed.

**Comment by agabrys** [comment]
You need to set `<force>true</force>` to force sources compilation.
Here is a list with all parameters: http://www.gabrys.biz/projects/lesscss-maven-plugin/RELEASE/compile-mojo.html

Now compiler compiles source file only when it or at least one dependency is changed.

I use this plugin at work and `compress` parameter works correctly. Can you prepare example?

**Comment by agabrys** [comment]
I need an example to solve your problem. Please prepare it or post a comment how you solved the problem.

**Comment by nitinsurana** [comment]
I still see /\* comments */ in the final compiled CSS. I'll try to have an example, but from what I can think this is the case :

```
main.less
@import (inline) "old_one.css"
@import (inline) "old_two.css"
@import "style.less"
@import "common.less"
```

Only less imports are compressed, everything else remains same.

**Comment by agabrys** [comment]
This is correct behavior. From [lesscss.org](http://lesscss.org/features/#import-options):

> **inline**: include the source file in the output but do not process it

To solve this you can import `old_one.css` and `old_two.css` using `less` option:

```
main.less
@import (less) "old_one.css"
@import (less) "old_two.css"
@import "style.less"
@import "common.less"
```

This will work if you didn't use any CSS _hacks_ in `*.css` files, example:

```
/* filter for IE6 and IE7 */
filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#444', EndColorStr='#999');
```

**Comment by nitinsurana** [comment]
Thanks a lot. I'll probably use r.js to compress the compiled CSS.
