### ISSUE TITLE
Issues with math with this compiler

### ISSUE THREAD

**Issue by SeabassNg** [gabrysbiz/lesscss-maven-plugin#2]
Compiling the bootstrap less source. We have the variable

@screen-xs-max: (@screen-sm-min - 1);

We have the following css property:

.hidden-xs {
    @media (max-width: @screen-xs-max) {
        .responsive-invisibility();
    }
}

The output for the above property looks like this:

@media (max-width:768px - 1){.hidden-xs{display:none !important}}

It should be

@media (max-width:767px){.hidden-xs{display:none !important}}

**Comment by agabrys** [comment]
I created an example and it works correctly.

pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>biz.gabrys.maven.plugins</groupId>
    <artifactId>lesscss-maven-plugin-issue-2</artifactId>
    <name>Issues with math with this compiler</name>
    <version>1.1</version>

    <build>
        <plugins>
            <plugin>
                <groupId>biz.gabrys.maven.plugins</groupId>
                <artifactId>lesscss-maven-plugin</artifactId>
                <version>1.1</version>
            </plugin>
        </plugins>
    </build>
</project>
```

src/main/less/source.less:

```
@screen-sm-min: 721px;
@screen-xs-max: (@screen-sm-min - 1);

.hidden-xs {
   @media (max-width: @screen-xs-max) {
      display: none;
   }
}
```

Execute `mvn biz.gabrys.maven.plugins:lesscss-maven-plugin:compile`

target/source.css:

```
@media (max-width: 720px) {
  .hidden-xs {
    display: none;
  }
}
```

Please create a sample project in which this issue occurred.

**Comment by SeabassNg** [comment]
I was compiling the Bootstrap less files. Have you tried it by having the variables defined in a different file from the .hidden-xs property and have the file that contains the property import the file with the variables?

**Comment by agabrys** [comment]
I created second example and it also works correctly.

pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>biz.gabrys.maven.plugins</groupId>
    <artifactId>lesscss-maven-plugin-issue-2</artifactId>
    <name>Issues with math with this compiler</name>
    <version>1.1</version>

    <build>
        <plugins>
            <plugin>
                <groupId>biz.gabrys.maven.plugins</groupId>
                <artifactId>lesscss-maven-plugin</artifactId>
                <version>1.1</version>
                <configuration>
                    <includes>
                        <include>source.less</include>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

src/main/less/source.less:

```
@import (reference) "variables.less";

.hidden-xs {
   @media (max-width: @screen-xs-max) {
      display: none;
   }
}
```

src/main/less/variables.less:

```
@screen-sm-min: 721px;
@screen-xs-max: (@screen-sm-min - 1);
```

Execute `mvn biz.gabrys.maven.plugins:lesscss-maven-plugin:compile`

target/source.css:

```
@media (max-width: 720px) {
  .hidden-xs {
    display: none;
  }
}
```

You need to prepare a working example that generates this issue (works incorrectly). Otherwise, I will not be able to solve your problem. It would be the best if you create an example project on GitHub and paste here the link.

**Comment by agabrys** [comment]
I close this issue due to the lack of response from the reporter.
